### ISSUE TITLE
BullShit

### ISSUE THREAD

**Issue by Toddi3D** [ankermake/AnkerMake-Marlin#2]
Brand new Printer with three years old Firmware. And a special Framework too. DONT BUY THIS PRINTER !!! ITS WORTH

**Comment by ipv6freely** [comment]
Very useful. Thanks.

**Comment by andrewseago** [comment]
Technically the firmware is from Sept 3, 2021. https://github.com/MarlinFirmware/Marlin/commit/cc3abcd2c50247dd934d49b91cc3b9460f1dc1a7

**Comment by andrewseago** [comment]
And I really like this printer. Despite it's Marlin 2.0.9.1 bugfix firmware.

**Comment by ipv6freely** [comment]
Yeah, just somebody that doesn't know how to use github and thinks it's for reviews, I guess?

**Comment by just-trey** [comment]
@ankermake, this request is spam I would suggest you close it.
